ci: version to 6.0.0 Micronaut 4.0.0-SNAPSHOT githubCoreBranch=4.0.x major version neo4j=4.4.10
micronaut-projects/micronaut-neo4j pull request #266
Opened 2022-08-09 18:53 UTC by wetted

- prepare for Micronaut 4 (no deprecated code found to remove)
- migrate neo4j from 3.5.x to 4.x with changes to `libs.versions.toml`, and fix breaking library code changes
- update docs

closes #256
closes #257

2022-08-09 19:00 UTC, wetted commented
All the Java 8 builds will fail. `neo4j` 4.x requires Java 11 or later.

2022-08-10 09:17 UTC, timyates commented
Does this want to be targetting the 6.0.0 branch instead of Master?

2022-08-16 11:45 UTC, sdelamo approved these changes

2022-08-16 15:18 UTC, wetted commented
> @wetted why does it fail?

@sdelamo The bolt driver fails to initialize with Java 17, with the error,
`io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.neo4j.bolt.Neo4jDriverFactory]`

I'm not yet sure why. It works just fine with Java 11.

2022-08-18 14:38 UTC, sdelamo requested changes
You have to remove `17` from the GraalVM github action https://github.com/micronaut-projects/micronaut-neo4j/blob/master/.github/workflows/graalvm.yml

2022-08-18 14:38 UTC, sdelamo commented on .github/workflows/gradle.yml
> +        java: ['11', '17']
remove 17

2022-08-18 14:42 UTC, sdelamo commented on build.gradle
> +java {
In the GCP project, which is only compatible to 11, we set the following in the [root build file](https://github.com/micronaut-projects/micronaut-gcp/blob/master/build.gradle#L7-L10)

```groovy

micronautBuild {
    sourceCompatibility = "11"
    targetCompatibility = "11"
}
```

2022-08-18 15:14 UTC, wetted commented on gradle.properties
> +micronautVersion=4.0.0-SNAPSHOT
> Target Micronaut 3.6.0 here. We will release a major version of Micronaut Neo4J module, but we will not include it in the Micronaut 3.6.x BOM.
> 
> Users, will be able to opt-in to Micronaut Neo4j 6 and use them in their Micronaut 3 applications, but they will have to explicitly set the version in the build files.

So I leave `githubCoreBranch=4.0.x` as is?

2022-09-01 10:02 UTC, sdelamo approved these changes

2022-09-01 10:02 UTC, sdelamo commented on gradle.properties
> +micronautVersion=4.0.0-SNAPSHOT
Yes.

2022-09-01 10:03 UTC, merged