change from disabling version catalog checks to suppressing checks of removals from library
micronaut-projects/micronaut-neo4j pull request #284
Opened 2022-10-06 16:08 UTC by wetted

2022-10-07 11:11 UTC, timyates requested changes

2022-10-07 11:11 UTC, timyates commented on neo4j-bom/build.gradle
> +        acceptedVersionRegressions.add("neo4j-driver-compat")
I think we only need:

```suggestion
        acceptedLibraryRegressions.add("neo4j")
        acceptedLibraryRegressions.add("neo4j-bolt")

        acceptedVersionRegressions.add("neo4j-compat")
        acceptedVersionRegressions.add("neo4j-driver-compat")
```

2022-10-07 14:38 UTC, sdelamo approved these changes
Thanks for this

2022-11-09 10:58 UTC, timyates approved these changes

2022-11-09 11:17 UTC, merged